### ISSUE TITLE
Please fix a  bug in groovy-devel

### ISSUE THREAD

**Issue by leehsiu** [ros-perception/slam_gmapping#18]
Hey guys,

There is a bug in the `groovy-devel`.

In `slam_gmapping.cpp`

``` c++
void
SlamGMapping::updateMap(const sensor_msgs::LaserScan& scan)
{
  boost::mutex::scoped_lock lock map_lock (map_mutex_);
  GMapping::ScanMatcher matcher;
  double* laser_angles = new double[scan.ranges.size()];
  double theta = angle_min_;
```

the `lock map_lock` should be removed.

Buy the way, I have finished a distribution of gmapping which is parallel, I will put it on github and send a merge request in order to share it .

**Comment by trigal** [comment]
Hi,

I wrote a parallel distribution of gmapping not long ago (this is why I was trying to compile in debug mode 10 months ago). With a little profiling I was able to have a good parallelism but only for the first minutes of the running, since after some time there was a part of code (now I don't remember exactly the function, I don't have the code with me right now) where inserting parallel sections gave me errors at runtime. 
Have you noticed something similar in your work? 
What kind of parallel technique did you use? openmp/intel tbb?

**Comment by tfoote** [comment]
For reference the line of code is: https://github.com/ros-perception/slam_gmapping/blob/hydro-devel/gmapping/src/slam_gmapping.cpp#L542

Why should that lock be removed? The function mutates map_ which is protected in that method as well as the callback.

**Comment by leehsiu** [comment]
I am so sorry to misunderstand the code but I mean that the 'lock' in that line should be removed in 'groovy-devel'  because it will lead to a synatx error when compiling.

**Comment by tfoote** [comment]
Sorry yes there is an extra "lock" in the middle. A pull request would be
appreciated.

**Comment by Zumili** [comment]
Hello the line:
boost::mutex::scoped_lock lock map_lock (map_mutex_);
must be replaced with:
boost::mutex::scoped_lock map_lock (map_mutex_);

so you have to delete the lost and forgotten "lock"

**Comment by vrabaud** [comment]
thx. Now releasing.
