### ISSUE TITLE
compile gmapping with debug options

### ISSUE THREAD

**Issue by trigal** [ros-perception/slam_gmapping#5]
Hi 

I'm trying to recompile the gmapping node with the debug options in order to perform some analysis with valgrind but I need to compile all the code in debug mode.

I've tried with set(ROS_BUILD_TYPE Debug) but it does not work..

does anyone have an idea? 

Augusto

**Comment by hershwg** [comment]
This package is a ROS wrapper around the gmapping code from openslam.informatik.uni-freiburg.de.  There is a little C++ source code in gmapping/src, and those files (main.cpp and slam_gmapping.cpp) should be successfully compiled with debug enabled when you set ROS_BUILD_TYPE. However all the core code of gmapping is inside a separate library which is downloaded and built by gmapping/Makefile.gmapping.  The ROS_BUILD_TYPE cmake variable is not transmitted into that makefile, which is my guess about why you are having trouble.

What I would do is do the download of the gmapping core source code by doing a regular build of slam_gmapping, then go back into the downloaded code's Makefile(s) and add "-g" compiler flags or whatever you need for debugging.  Then recompile the core library and the outer wrapper, and you should be good.

Once you get it working, you could create a .patch file which represents the change between normal and debug compilation and put that in the gmapping directory.  Then gmapping/CMakeLists.txt could check for ROS_BUILD_TYPE==Debug and pass a flag through the execute_process() call to Makefile.gmapping, which would then conditionally apply the patch only if Debug mode was desired.

**Comment by trigal** [comment]
Hi, thx for the answer. Ok, I did the following steps
- compiled normally with make in the gmapping folder (same as rosmake)
- checked the files generated/downloaded I found the /home/augusto/rosbuild_ws/gmapping/build/gmapping_export folder that contains the manual.mk file (included in global.mk) which has these interesting lines:
  <pre>
  1 #CPPFLAGS+= -DNDEBUG 
  2 CXXFLAGS+= -O3 -Wall -ffast-math
  3 #CXXFLAGS+= -g -O0 -Wall 
  4 PROFILE= false
  </pre>
  as you can see these are clearly the lines where we can switch in debug compile mode with no optimizations. So I created a little patch to enable the correct flags and another one to change Makefile.gmapping. 

I don't really know how to pass a flag through the execute_process function, sorry. 

If you want I can upload the 2 little patches here, let me know. 

Thx again for your help,
Augusto

**Comment by hershwg** [comment]
Looks like the way to do it is via environment variables.  You can set an environment variable within the CMakeLists.txt like so:

set(ENV{GMAPPING_COMPILATION_MODE} debug)

Then the existing
execute_process(COMMAND cmake -E chdir ${PROJECT_SOURCE_DIR} make -f Makefile.gmapping
                RESULT_VARIABLE _make_failed)
will pass that environment variable through into the "make" command, and the variable will appear as a variable in Makefile.gmapping.

Then in Makefile.gmapping you can use the '?=' operator to assign a default value if the environment does not specify it:

GMAPPING_COMPILATION_MODE?=release

Finally in Makefile.gmapping you would want a conditional to set your CXXFLAGS:

ifeq ($(GMAPPING_COMPILATION_MODE),debug)
        CXXFLAGS+= -g -O0 -Wall
else
        CXXFLAGS+= -O3 -Wall -ffast-math
endif

Of course way back in the CMakeLists.txt file we should do our set(ENV{GMAPPING... call inside a conditional, or maybe just set it equal to ROS_BUILD_TYPE and then change the downstream things to use "Debug" instead of debug, and also support "RelWithDebInfo", which is quite useful.

If you want to implement all this based on my comments, it would be a help.  If not, sounds like I kind of know how to do it. :)

**Comment by trigal** [comment]
Hi :-)

I've just tried to apply these changes but the Makefile.gmapping fails with the <CXXFLAGS+= -g -O0 -Wall> line

<pre>
ifeq ($(GMAPPING_COMPILATION_MODE),debug)
CXXFLAGS+= -g -O0 -Wall
else
CXXFLAGS+= -O3 -Wall -ffast-math
endif
</pre>

to be sure that the error is not in the _ifeq_ instruction I tried to leave only the _CXXFLAGS+= -g -O0 -Wall_ line, same error.

<pre>
ifeq (Debug,Debug)
/bin/sh: 1: Syntax error: word unexpected (expecting ")")
make[1]: *** [installed] Error 2
make[1]: Leaving directory `/home/augusto/rosbuild_ws/gmapping'
CMake Error at CMakeLists.txt:13 (message):
  Build of GMapping failed
</pre>

I completely agree with your solution but, as I previously said, at the moment I'm not very good with the makefiles :(

Now i'm going to test gmapping with the debug options enabled with my static patch files, as soon as I have time I'll try again with more effort.

**Comment by vrabaud** [comment]
ok, all that code is now properly wrapped. Just refer to: https://github.com/ros-perception/openslam_gmapping
