### ISSUE TITLE
catkinizated package has different name

### ISSUE THREAD

**Issue by mikeferguson** [ros-perception/slam_gmapping#6]
Pre-catkinization, the stack was slam_gmapping, the package was gmapping.. currently, the upstream repo is now "gmapping" and this stack has become "slam_gmapping" -- this breaks any launch file or docs from previous versions.

**Comment by vrabaud** [comment]
Sure, what do you suggest ? "gmapping" makes sense as a 3rd party that's why I named it this way
We could rename slam_gmapping to be whatever (gmapping_ros ?) but that would not solve your problem.
Suggestions for gmapping if we want to keep bc (then again, catkinization would be a good moment to break things as I doubt many packages depend on it):
- gmapping_3rd_party
- gmapping_upstream
- gmapping_non_ros

**Comment by tfoote** [comment]
You could call the upstream openslam_gmapping?

**Comment by vrabaud** [comment]
I like that. Any other sugggestion before I use that ?

**Comment by mikeferguson** [comment]
+1 to openslam_gmapping

**Comment by mikeferguson** [comment]
I created two pull requests for this: https://github.com/ros-perception/gmapping/pull/1 and https://github.com/ros-perception/slam_gmapping/pull/8

**Comment by wjwwood** [comment]
+1 to both pull requests.

We should try to get these out asap for the Hydro Beta. Let me know if I can help.

**Comment by mikeferguson** [comment]
@wjwwood I think it's safe to merge these, however, there are still other issues -- while it builds, gmapping segfaults real fast.

**Comment by wjwwood** [comment]
@mikeferguson Ok, I'll merge these, rename the other repo and see if I can reproduce the segfaults.
